value1 = input('Digite um valor: ')
print('O tipo primitivo desse valor é ', type(value1))
print('Esse valor só tem espaços? ', value1.isspace())
print('Esse valor é um número? ', value1.isnumeric())
print('Esse valor é alfabético? ', value1.isalpha())
print('Esse valor é alfanumérico? ', value1.isalnum())
print('Esse valor está em letras maiúsculas? ', value1.isupper())
print('Esse valor está em letras minúsculas? ', value1.islower())
print('Está capitalizada? ', value1.istitle())
